'use client';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from '@/components/ui/accordion';
import organizers from './organizers.json';
import site from '../site.config.json';
const base = import.meta.env.BASE_URL;
const stages = [
 {id:'post',n:'01',title:'The post',question:'Before I believe it, what can I check?',record:'A news-like video, its description, and visible source cues.',task:'Compare the claim with the sources a viewer can actually inspect. Separate a signal of authority from evidence of verification.',example:'A post says “according to a source” but provides no link. What could a viewer check before sharing?',output:'A question about how a particular cue or action affects a user decision.',color:'blue'},
 {id:'spread',n:'02',title:'The spread',question:'When I share it, what travels with it?',record:'An excerpt, a repost, comments, and the context that each preserves or omits.',task:'Follow what changes when the claim moves. Identify what another viewer can inspect, and how the person named can respond.',example:'A clipped version circulates without the original description. What context could the sharing interface preserve?',output:'A question about context, interpretation, or response during circulation.',color:'green'},
 {id:'aftermath',n:'03',title:'The aftermath',question:'Would I ever see the correction?',record:'Later reporting, responses, corrections, or a court outcome.',task:'Distinguish the existence of later information from evidence that earlier viewers encountered or understood it.',example:'A ruling is reported months later. What route could bring that update to someone who saw the original claim?',output:'A question about the delivery, understanding, or use of later information.',color:'purple'}
];
const sessions = [
 {n:'01',title:'Build a shared picture',subtitle:'90 minutes · Common ground and participants’ contexts',rows:[['10','Opening scene','Look at a labeled composite post. Write what you would check before believing or sharing.'],['25','Panel conversation','Hear a journalist, a platform practitioner, and a policy voice connect a case to one consequential decision. Speakers to be confirmed.'],['45','Lightning contributions','Up to fifteen three-minute talks, each bringing one situation and one question.'],['10','Find your group','Choose the post, spread, or aftermath. We balance groups across experiences and contexts.']]},
 {n:'02',title:'Turn observations into questions',subtitle:'90 minutes · Group work, exchange, and synthesis',rows:[['35','Work with a case','In pairs or trios, connect a record to interface cues, user actions, unknowns, and a research question.'],['15','Assemble the sequence','Each group shares its findings. Keep documented, unknown, and disputed items visible.'],['20','Try the idea elsewhere','Exchange worksheets. Ask what a design or practice would need to work at another stage or in another context.'],['20','Choose what comes next','Propose and rank research questions, retain dissent, and find volunteer owners and next steps.']]}
];
export default function Home(){return <>
<a className="skip" href="#main">Skip to content</a>
<div className="prototype">PARTICIPANT GUIDE PROTOTYPE <span>Proposed for CHI 2027 · Acceptance pending · Submissions not open</span></div>
<header className="masthead"><a className="wordmark" href="#main" aria-label="News Without Newsrooms, top">N<span>/</span>N</a><nav aria-label="Main navigation"><a href="#experience">Workshop</a><a href="#program">Program</a><a href="#participate">Take part</a><a href="#organizers">People</a></nav><span className="edition">JOURNALISM × HCI</span></header>
<main id="main">
<section className="hero"><div><p className="eyebrow">BELIEF. SPREAD. AFTERMATH.</p><h1>News<br/>Without<br/><em>Newsrooms.</em></h1><p className="lede">When a post looks like news, what can people see, verify, and do?</p><p className="intro">Bring one situation and one question. Work with people from journalism, HCI, AI, and policy to examine how claims travel and how later information reaches us.</p><a className="button" href="#experience">Explore the workshop <span>↗</span></a></div><div className="hero-sequence"><span className="eyebrow">ONE CLAIM. THREE MOMENTS.</span>{stages.map(s=><a href={'#'+s.id+'-question'} className="sequence-step" key={s.id}><span>{s.n}</span><div><h2>{s.title}</h2><p>{s.question}</p></div><b aria-hidden="true">↓</b></a>)}<div className="sequence-bottom">A shared case becomes<br/><strong>a set of research questions.</strong></div></div></section>
<div className="facts"><p>PROPOSED VENUE<strong>CHI 2027 · Pittsburgh · May 2027</strong></p><p>FORMAT<strong>In person · Two 90-minute sessions</strong></p><p>GROUP SIZE<strong>15–25, including organizers</strong></p></div>
<section className="section" id="experience"><div className="section-heading"><div><p className="eyebrow">01 / WHAT WE WILL DO</p><h2 className="section-title">Follow the claim.<br/><em>Work on the decisions.</em></h2></div><p className="section-lede">We start with documented accusation-video cases, then bring in participants’ own contexts. The shared question is about people: what can a viewer inspect, a sharer pass on, or a person accused do in response?</p></div>
<div className="stage-questions">{stages.map(s=><article id={s.id+'-question'} key={s.id}><span className="small-number">{s.n}</span><h3>{s.title}</h3><p>{s.question}</p></article>)}</div>
<figure className="overview"><img src={`${base}workshop-overview.png`} width="2200" height="1100" alt="A labeled composite post alongside a schematic case sequence. Case records extend to different points; audience exposure remains a separate evidence question."/><figcaption><span>THE STARTING MATERIAL</span> A composite interface and a shared case map. The image illustrates the exercise; it does not depict a real person or post. <a href={`${base}workshop-overview.png`} target="_blank" rel="noreferrer">Open full-size figure ↗</a></figcaption></figure>
<p className="tab-instruction">Choose a stage to see what your group will work with.</p>
<Tabs defaultValue="post" className="stage-tabs"><TabsList className="stage-tab-list" aria-label="Explore the three working groups">{stages.map(s=><TabsTrigger key={s.id} value={s.id} className="stage-trigger"><span>{s.n}</span>{s.title}</TabsTrigger>)}</TabsList>{stages.map(s=><TabsContent key={s.id} value={s.id} className="stage-panel"><div><p className="eyebrow">AT YOUR GROUP</p><h3>{s.question}</h3><p>{s.task}</p><dl><dt>Material</dt><dd>{s.record}</dd><dt>You produce</dt><dd>{s.output}</dd></dl></div><aside className="example"><p className="eyebrow">ILLUSTRATIVE PROMPT</p><blockquote>{s.example}</blockquote><p>Keep what is documented, what is unknown, and where you disagree separate.</p></aside></TabsContent>)}</Tabs>
<div className="group-flow"><div><span className="flow-kicker">HOW WE WORK TOGETHER</span><h3>Small groups.<br/>A shared sequence.</h3><p>Start in pairs or trios within a stage group. Then exchange your worksheet with another group to test an idea in a different context.</p><a className="text-link" href={`${base}worksheet.html`} target="_blank" rel="noreferrer">Preview the common worksheet ↗</a></div><div className="group-map" role="img" aria-label="Three working groups: post exchanges with spread, spread with aftermath, and aftermath with post. These are groupings, not a fixed room layout.">{stages.map(s=><div className={'group-node '+s.color} key={s.id}><div className="dots" aria-hidden="true">● ● ●</div><strong>{s.title}</strong><div className="dots" aria-hidden="true">● ● ●</div><span className="exchange" aria-hidden="true">→</span></div>)}<p>Post → Spread → Aftermath → Post<br/><span>Group arrangement adapts to attendance and the room.</span></p></div></div>
</section>
<section className="program section" id="program"><p className="eyebrow">02 / THE PROPOSED PROGRAM</p><h2 className="section-title">A conversation.<br/><em>Then something to build on.</em></h2><p className="section-lede">A panel and short contributions give us common ground. The second session is for working with cases and shaping research questions together.</p><div className="sessions">{sessions.map(s=><article className="session" key={s.n}><div className="session-head"><span>{s.n}</span><div><h3>{s.title}</h3><p>{s.subtitle}</p></div></div><ol>{s.rows.map(([mins,title,description])=><li key={title}><div className="duration"><strong>{mins}</strong><span>MIN</span></div><div><h4>{title}</h4><p>{description}</p></div></li>)}</ol></article>)}</div><div className="program-note"><span>BETWEEN SESSIONS</span><p>A conference-assigned break. The current plan allows 30 minutes; final timing and room details will follow acceptance. If sessions are 75 minutes, every activity remains with shorter segments.</p></div></section>
<section className="section participation" id="participate"><div><p className="eyebrow">03 / WHAT TO BRING</p><h2 className="section-title">One situation.<br/><em>One question.</em></h2><p className="section-lede">A case, interface, study, design, or argument that others can work with. You do not need expertise in every field, or prior knowledge of the Korean cases.</p><p>We welcome HCI and AI researchers, system designers, journalists, creators, and platform and policy practitioners. Cases from different places help us examine where a comparison holds and where it breaks.</p><div className="planned-date"><span>PLANNED CONTRIBUTION DEADLINE</span><strong>11 February 2027</strong><p>Anywhere on Earth · Subject to workshop acceptance</p></div></div><div className="contribution-options"><article><span className="option-number">A</span><h3>Position paper</h3><p className="format">2–4 pages · ACM single-column · Not anonymized</p><p>Describe a case, design, study, or argument. Make one concrete situation and a question for the room clear.</p></article><article><span className="option-number">B</span><h3>Practitioner statement</h3><p className="format">1 page</p><p>Share a situation from practice, the decision it raised, and one question you would like to explore with others.</p></article><p className="submission-note">If accepted, the call will open on 17 December 2026 with email submission instructions. Two organizers will review each contribution for relevance, a concrete situation, and a workable question. This prototype is not accepting submissions.</p></div></section>
<section className="prepare section" id="prepare"><p className="eyebrow">04 / BEFORE YOU ARRIVE</p><h2 className="section-title">Enough shared ground<br/><em>to get straight to work.</em></h2><div className="prepare-grid"><article><span>01</span><h3>Read the case pack</h3><p>Two weeks before the workshop, we plan to share the reference sequence, comparison records, checked English translations of Korean material, and the worksheet.</p></article><article><span>02</span><h3>Locate your question</h3><p>Choose a point in the post, spread, or aftermath. Note what your record shows, what it cannot tell us, and what another perspective could help you understand.</p></article><article><span>03</span><h3>Prepare to contribute</h3><p>Selected contributors will give a three-minute talk using a shared slide file. Others introduce their contribution in their group. Discussion continues through question cards.</p></article></div><div className="material-link"><div><strong>The worksheet is already available to preview.</strong><p>Seven prompts connect a record to a research question. The case pack will be prepared and reviewed before release.</p></div><a className="button" href={`${base}worksheet.html`} target="_blank" rel="noreferrer">Open worksheet <span>↗</span></a></div></section>
<section className="section outcomes"><p className="eyebrow">05 / WHAT WE LEAVE WITH</p><div className="outcome-grid"><h2 className="section-title">Questions with<br/><em>a next step.</em></h2><ol><li><span>01</span><div><h3>A shared sequence</h3><p>Records, interface cues, user actions, unknowns, and disagreement assembled across the three groups.</p></div></li><li><span>02</span><div><h3>Research questions to pursue</h3><p>Situated questions, volunteer owners, and practical next steps. The group keeps dissent visible.</p></div></li><li><span>03</span><div><h3>A reusable foundation</h3><p>A participant-reviewed report within six weeks, continued access to the case pack, and an autumn 2027 online follow-up.</p></div></li></ol></div></section>
<section className="section people" id="organizers"><p className="eyebrow">06 / THE ORGANIZERS</p><div className="section-heading"><h2 className="section-title">Different expertise.<br/><em>A shared task.</em></h2><p className="section-lede">News systems, public communication, policy, AI, and product development come together in the planning and facilitation of the workshop.</p></div><div className="people-grid">{organizers.map(o=><article key={o.name}><h3>{o.name}</h3><p className="affiliation">{o.affiliation}</p><p>{o.name==='Shree Saikia'?'Will help prepare questions about journalistic verification and correction and support the aftermath-stage discussion.':o.bio[0].toUpperCase()+o.bio.slice(1)}</p></article>)}</div></section>
<section className="section faq"><p className="eyebrow">07 / PRACTICAL QUESTIONS</p><div className="faq-layout"><h2 className="section-title">Before you<br/><em>make plans.</em></h2><Accordion className="questions"><AccordionItem value="status"><AccordionTrigger>Is this workshop confirmed?</AccordionTrigger><AccordionContent>No. This is a participant guide prototype for a proposed CHI 2027 workshop. Acceptance is pending. The program, participation process, and dates will be finalized if the workshop is accepted.</AccordionContent></AccordionItem><AccordionItem value="attend"><AccordionTrigger>Can I join without an accepted contribution?</AccordionTrigger><AccordionContent>The proposed workshop will prioritize accepted contributors and remain open to conference attendees, subject to capacity and CHI’s attendance arrangements. The same materials and group activities will be available to everyone who joins.</AccordionContent></AccordionItem><AccordionItem value="access"><AccordionTrigger>What about language and accessibility?</AccordionTrigger><AccordionContent>The workshop will be conducted in English, with checked English translations of Korean case records. We plan accessible materials and will request live captioning. Contact the organizers about access needs so we can plan with you; specific services are not yet confirmed.</AccordionContent></AccordionItem><AccordionItem value="recording"><AccordionTrigger>Will my contribution be published or recorded?</AccordionTrigger><AccordionContent>Contributions will be posted only with author consent; authors retain copyright. Panel recording requires consent. Participants can contribute without attribution, and the workshop report will be reviewed by participants. This is a design workshop, not a participant study.</AccordionContent></AccordionItem></Accordion></div></section>
</main><footer><div className="footer-title">News Without<br/><em>Newsrooms.</em></div><div><p>Questions about the workshop?</p><a href={`mailto:${site.contactEmail}`}>{site.contactEmail} ↗</a><p className="footer-note">Participant guide prototype for a proposed CHI 2027 workshop.<br/>Acceptance pending. Program and participation details are provisional.</p><a className="official" href="https://chi2027.acm.org/authors/workshops/" target="_blank" rel="noreferrer">CHI 2027 workshop information ↗</a></div></footer>
</>}
